{% set name = "h2" %}
{% set version = "3.2.0" %}
{% set sha256 = "875f41ebd6f2c44781259005b157faed1a5031df3ae5aa7bcb4628a6c0782f14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - hyperframe    >=5.1.0,<6
    - hpack         >=2.3,<4
    - enum34        >=1.1.6,<2  # [py2k]

test:
  imports:
    - h2

about:
  home: http://python-hyper.org/h2/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'HTTP/2 State-Machine based protocol implementation'
  dev_url: https://github.com/python-hyper/hyper-h2

extra:
  recipe-maintainers:
    - primozgodec
