{% set name = "h2" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8a52129695e88b1a0578d8d2cc6842bbd79128ac685463b887ee278126ad01f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - hyperframe    >=6.0,<7
    - hpack         >=4.0,<5

test:
  imports:
    - h2

about:
  home: http://python-hyper.org/h2/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: HTTP/2 State-Machine based protocol implementation
  dev_url: https://github.com/python-hyper/hyper-h2

extra:
  recipe-maintainers:
    - primozgodec
    - wiphoo
