# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gruajLPAWrXGyyVGVz2KOKFtW69IOX6iHqjwQThLqoTiFLknTNHOgB0PypN2mIL1qGV74bOHqTQtW1Grm4sv7cjvjqhfmYq2STnNWFAjzKrOfo2EXxhm6eiOm+lMYtg/w1+4QZIaZmtmz4KkWzyu+rMnYvlYusR+W65eXBL6bIbuZaa+VfuNUD4VZXkQwM9c2171KYoW6XOj5ME/sr4cgA5XESTSf3n2xWHARLEEHMdVfB2aUyMNTbv13IBsWc+62vQ3Di7rEVdi8fTdGD0QYbdFETnaJbmaIEwTWvfQkmqv8yOHTGNFgsKryR44Jc1yrf2rWndNUSXI6IDzZamDAduSN1ts5AfoIUY4RXd9pE2Js+v++3OxuP5TRfGB34dNqreqxy4/g8BlIgcKBnQ9oV+bRK3XYy/YxsPLWbsvY2B1nxP8JOVq16b9cyJLKj8g55rGxoCtruvsr7wVbHf/Pt/GubW6bifHp1ap9DkQoFgExo61R/Yy57hamBi4hGbK6iLF98J5yfw1V8A9DDxtXRsDG3W4CFBhQWJS1X1B3BkFBSHC1mFRwnwRWWhVamMhPOs76L+kPsByQa/tdDeqcBubWpCWxMrwZZZI2LpB04IVD36Z5j+uShOa1DYjgcBnyvQgr5bDmdCfxHbxOvGWav7QgAnVhVF2P6dLrqj00/s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
