travis:
  secure:
    BINSTAR_TOKEN: gruajLPAWrXGyyVGVz2KOKFtW69IOX6iHqjwQThLqoTiFLknTNHOgB0PypN2mIL1qGV74bOHqTQtW1Grm4sv7cjvjqhfmYq2STnNWFAjzKrOfo2EXxhm6eiOm+lMYtg/w1+4QZIaZmtmz4KkWzyu+rMnYvlYusR+W65eXBL6bIbuZaa+VfuNUD4VZXkQwM9c2171KYoW6XOj5ME/sr4cgA5XESTSf3n2xWHARLEEHMdVfB2aUyMNTbv13IBsWc+62vQ3Di7rEVdi8fTdGD0QYbdFETnaJbmaIEwTWvfQkmqv8yOHTGNFgsKryR44Jc1yrf2rWndNUSXI6IDzZamDAduSN1ts5AfoIUY4RXd9pE2Js+v++3OxuP5TRfGB34dNqreqxy4/g8BlIgcKBnQ9oV+bRK3XYy/YxsPLWbsvY2B1nxP8JOVq16b9cyJLKj8g55rGxoCtruvsr7wVbHf/Pt/GubW6bifHp1ap9DkQoFgExo61R/Yy57hamBi4hGbK6iLF98J5yfw1V8A9DDxtXRsDG3W4CFBhQWJS1X1B3BkFBSHC1mFRwnwRWWhVamMhPOs76L+kPsByQa/tdDeqcBubWpCWxMrwZZZI2LpB04IVD36Z5j+uShOa1DYjgcBnyvQgr5bDmdCfxHbxOvGWav7QgAnVhVF2P6dLrqj00/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
